[package]
name = "untitled_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = { version = "0.20", default-features = false, features = ["crossterm-backend"] }
spinoff = "0.8.0"
